### ISSUE TITLE
Todo  기능 요구서

### ISSUE THREAD

**Issue by ye2un** [ye2un/TodoApp#2]
- [x] 코멘트 기능 추가
- [x] 날짜 추가 
- [x] 완료 기능 추가
- [x] 우선 순위 추가

**Comment by ye2un** [comment]
- [ ] 카테고리 추가

**Comment by ye2un** [comment]
END~!
